FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN mkdir -p /app/node_modules

RUN npm config set unsafe-perm true
RUN npm install

COPY . .

RUN chown -R node:node /app/node_modules


CMD ["npm", "run", "start"]